/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shuqy_bgm_service_BGMService */

#ifndef _Included_com_shuqy_bgm_service_BGMService
#define _Included_com_shuqy_bgm_service_BGMService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shuqy_bgm_service_BGMService
 * Method:    checkPlayer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_shuqy_bgm_service_BGMService_checkPlayer
  (JNIEnv *, jobject);

/*
 * Class:     com_shuqy_bgm_service_BGMService
 * Method:    initNativeDll
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_shuqy_bgm_service_BGMService_initNativeDll
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_shuqy_bgm_service_BGMService
 * Method:    nativeGc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_shuqy_bgm_service_BGMService_nativeGc
  (JNIEnv *, jobject);

/*
 * Class:     com_shuqy_bgm_service_BGMService
 * Method:    getMusicTitle
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_shuqy_bgm_service_BGMService_getMusicTitle
  (JNIEnv *, jobject);

/*
 * Class:     com_shuqy_bgm_service_BGMService
 * Method:    getCurrentPosition
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_shuqy_bgm_service_BGMService_getCurrentPosition
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
